import { DEFAULT_COMMON_SETTINGS } from '@lobechat/const';
import { z } from 'zod';

import { type Def, def, UI_CLIENTS } from './registryShared';

const animationModeSchema = z.enum(['disabled', 'agile', 'elegant']);
const transitionModeSchema = z.enum(['smooth', 'fadeIn', 'none']);

export const GENERAL_ENTRIES: readonly Def[] = [
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: DEFAULT_COMMON_SETTINGS.fontSize,
    control: 'number',
    descriptionKey: 'settingsPolicy.paths.general.fontSize.desc',
    group: 'general',
    max: 24,
    min: 12,
    path: 'general.fontSize',
    userControlSurface: {
      kind: 'surface',
      surfaceFile: 'src/routes/(main)/settings/chat-appearance/features/ChatAppearance/index.tsx',
    },
    platformPolicyEligible: true,
    schema: z.number().int().min(12).max(24),
    schemaVersion: 1,
    sensitivity: 'public',
    step: 1,
    titleKey: 'settingsPolicy.paths.general.fontSize.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: DEFAULT_COMMON_SETTINGS.animationMode ?? 'agile',
    control: 'select',
    descriptionKey: 'settingsPolicy.paths.general.animationMode.desc',
    group: 'general',
    options: [
      { labelKey: 'settingsPolicy.options.animation.disabled', value: 'disabled' },
      { labelKey: 'settingsPolicy.options.animation.agile', value: 'agile' },
      { labelKey: 'settingsPolicy.options.animation.elegant', value: 'elegant' },
    ],
    path: 'general.animationMode',
    userControlSurface: {
      kind: 'surface',
      surfaceFile: 'src/routes/(main)/settings/common/features/Common/Common.tsx',
    },
    platformPolicyEligible: true,
    schema: animationModeSchema,
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.animationMode.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: DEFAULT_COMMON_SETTINGS.telemetry,
    control: 'switch',
    descriptionKey: 'settingsPolicy.paths.general.telemetry.desc',
    group: 'general',
    path: 'general.telemetry',
    userControlSurface: {
      kind: 'surface',
      surfaceFile: 'src/routes/(main)/settings/about/features/Analytics.tsx',
    },
    platformPolicyEligible: true,
    schema: z.boolean(),
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.telemetry.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: DEFAULT_COMMON_SETTINGS.isLiteMode,
    control: 'switch',
    descriptionKey: 'settingsPolicy.paths.general.isLiteMode.desc',
    group: 'general',
    path: 'general.isLiteMode',
    userControlSurface: { kind: 'none', reason: 'No dedicated settings control in main SPA' },
    platformPolicyEligible: true,
    schema: z.boolean(),
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.isLiteMode.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: DEFAULT_COMMON_SETTINGS.transitionMode ?? 'fadeIn',
    control: 'select',
    descriptionKey: 'settingsPolicy.paths.general.transitionMode.desc',
    group: 'general',
    options: [
      { labelKey: 'settingsPolicy.options.transition.smooth', value: 'smooth' },
      { labelKey: 'settingsPolicy.options.transition.fadeIn', value: 'fadeIn' },
      { labelKey: 'settingsPolicy.options.transition.none', value: 'none' },
    ],
    path: 'general.transitionMode',
    userControlSurface: {
      kind: 'surface',
      surfaceFile: 'src/routes/(main)/settings/chat-appearance/features/ChatAppearance/index.tsx',
    },
    platformPolicyEligible: true,
    schema: transitionModeSchema,
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.transitionMode.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: DEFAULT_COMMON_SETTINGS.costEstimateWarningThreshold ?? 2,
    control: 'number',
    descriptionKey: 'settingsPolicy.paths.general.costEstimateWarningThreshold.desc',
    group: 'general',
    max: 100,
    min: 0,
    path: 'general.costEstimateWarningThreshold',
    userControlSurface: { kind: 'none', reason: 'No dedicated settings control in main SPA' },
    platformPolicyEligible: true,
    schema: z.number().min(0).max(100),
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.costEstimateWarningThreshold.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: true,
    control: 'switch',
    descriptionKey: 'settingsPolicy.paths.general.enableAutoScrollOnStreaming.desc',
    group: 'general',
    path: 'general.enableAutoScrollOnStreaming',
    userControlSurface: {
      kind: 'surface',
      surfaceFile: 'src/routes/(main)/settings/chat-appearance/features/ChatAppearance/index.tsx',
    },
    platformPolicyEligible: true,
    schema: z.boolean(),
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.enableAutoScrollOnStreaming.title',
  }),
  def({
    applicableClients: UI_CLIENTS,
    builtInDefault: true,
    control: 'switch',
    descriptionKey: 'settingsPolicy.paths.general.enableMessageLinkIcon.desc',
    group: 'general',
    path: 'general.enableMessageLinkIcon',
    userControlSurface: {
      kind: 'surface',
      surfaceFile: 'src/routes/(main)/settings/chat-appearance/features/ChatAppearance/index.tsx',
    },
    platformPolicyEligible: true,
    schema: z.boolean(),
    schemaVersion: 1,
    sensitivity: 'public',
    titleKey: 'settingsPolicy.paths.general.enableMessageLinkIcon.title',
  }),
  // responseLanguage / timezone intentionally omitted: no schema-valid built-in default
  // and optional absence is not modeled as a forced string leaf.
];
