/**
 * Stable enterprise business error codes.
 * UI maps codes — never free-text stack traces.
 *
 * Prefix rules (M00):
 * - PLATFORM_* — platform / revision / config / infra
 * - ADMIN_*    — admin console / reauth / reason gates
 * - MANAGED_*  — managed resource / setting enforcement
 * - RESOURCE_* — M06 canonical compatibility spelling for legacy mutation denial
 */

export const PLATFORM_ERROR_CODES = {
  PLATFORM_PERMISSION_DENIED: 'PLATFORM_PERMISSION_DENIED',
  PLATFORM_REVISION_CONFLICT: 'PLATFORM_REVISION_CONFLICT',
  PLATFORM_CONFIG_VALIDATION_FAILED: 'PLATFORM_CONFIG_VALIDATION_FAILED',
  PLATFORM_AGENT_DEPENDENCY_UNAVAILABLE: 'PLATFORM_AGENT_DEPENDENCY_UNAVAILABLE',
  PLATFORM_AGENT_START_FAILED: 'PLATFORM_AGENT_START_FAILED',
  PLATFORM_AGENT_UNAVAILABLE: 'PLATFORM_AGENT_UNAVAILABLE',
  PLATFORM_GLOBAL_CREDENTIAL_FILE_PAYLOAD_INVALID:
    'PLATFORM_GLOBAL_CREDENTIAL_FILE_PAYLOAD_INVALID',
  PLATFORM_SECRET_REQUIRED: 'PLATFORM_SECRET_REQUIRED',
  PLATFORM_SECRET_NOT_READABLE: 'PLATFORM_SECRET_NOT_READABLE',
  PLATFORM_AI_MODEL_NOT_PUBLISHED: 'PLATFORM_AI_MODEL_NOT_PUBLISHED',
  PLATFORM_AI_MODEL_PULL_DISABLED: 'PLATFORM_AI_MODEL_PULL_DISABLED',
  /** Known managed provider is present but administratively disabled — fail closed, no BYOK. */
  PLATFORM_AI_PROVIDER_DISABLED: 'PLATFORM_AI_PROVIDER_DISABLED',
  /**
   * Admin runtime catalog fetch failed for one or more providers in a batch.
   * Client must not treat missing providers as an empty model catalog.
   */
  PLATFORM_AI_PROVIDER_PARTIAL_LOAD: 'PLATFORM_AI_PROVIDER_PARTIAL_LOAD',
  PLATFORM_RESOURCE_IN_USE: 'PLATFORM_RESOURCE_IN_USE',
  PLATFORM_DEFAULT_AGENT_REQUIRED: 'PLATFORM_DEFAULT_AGENT_REQUIRED',
  PLATFORM_ACTIVATION_RESTART_REQUIRED: 'PLATFORM_ACTIVATION_RESTART_REQUIRED',
  PLATFORM_ROLLOUT_PARTIAL_FAILURE: 'PLATFORM_ROLLOUT_PARTIAL_FAILURE',
  PLATFORM_OIDC_DISCOVERY_FAILED: 'PLATFORM_OIDC_DISCOVERY_FAILED',
  PLATFORM_OIDC_CLAIM_VALIDATION_FAILED: 'PLATFORM_OIDC_CLAIM_VALIDATION_FAILED',
  PLATFORM_OIDC_RESTART_UNSUPPORTED: 'PLATFORM_OIDC_RESTART_UNSUPPORTED',
  PLATFORM_OIDC_RESTART_NOT_PENDING: 'PLATFORM_OIDC_RESTART_NOT_PENDING',
  PLATFORM_OIDC_RESTART_INTENT_INVALID: 'PLATFORM_OIDC_RESTART_INTENT_INVALID',
  PLATFORM_OIDC_RESTART_INTENT_EXPIRED: 'PLATFORM_OIDC_RESTART_INTENT_EXPIRED',
  PLATFORM_SSRF_BLOCKED: 'PLATFORM_SSRF_BLOCKED',
  PLATFORM_FEATURE_DISABLED: 'PLATFORM_FEATURE_DISABLED',
  /**
   * A deployment module is switched off (env or DB). Always FORBIDDEN — never
   * NOT_FOUND — so the client can show "module disabled" instead of a retry loop.
   */
  PLATFORM_MODULE_DISABLED: 'PLATFORM_MODULE_DISABLED',
  PLATFORM_LAST_SUPER_ADMIN: 'PLATFORM_LAST_SUPER_ADMIN',
  PLATFORM_NOT_FOUND: 'PLATFORM_NOT_FOUND',
  PLATFORM_INVALID_INPUT: 'PLATFORM_INVALID_INPUT',
  PLATFORM_ASSET_STORAGE_UNAVAILABLE: 'PLATFORM_ASSET_STORAGE_UNAVAILABLE',
  PLATFORM_IDEMPOTENCY_CONFLICT: 'PLATFORM_IDEMPOTENCY_CONFLICT',
  /**
   * 内容审计 blocked the request before it reached the model (policy action = block).
   * Error body carries `{ message, category, recordId }` for the conversation error card.
   */
  PLATFORM_CONTENT_MODERATION_BLOCKED: 'PLATFORM_CONTENT_MODERATION_BLOCKED',
  /** 网络代理: scope configured `onUnavailable: 'fail'` and the outlet is down (user-visible). */
  PLATFORM_NETWORK_PROXY_UNAVAILABLE: 'PLATFORM_NETWORK_PROXY_UNAVAILABLE',
  PLATFORM_NETWORK_PROXY_ENGINE_NOT_INSTALLED: 'PLATFORM_NETWORK_PROXY_ENGINE_NOT_INSTALLED',
  PLATFORM_NETWORK_PROXY_ARTIFACT_MISMATCH: 'PLATFORM_NETWORK_PROXY_ARTIFACT_MISMATCH',
  PLATFORM_NETWORK_PROXY_UNSUPPORTED_PLATFORM: 'PLATFORM_NETWORK_PROXY_UNSUPPORTED_PLATFORM',
  PLATFORM_NETWORK_PROXY_ENGINE_ERROR: 'PLATFORM_NETWORK_PROXY_ENGINE_ERROR',
  PLATFORM_NETWORK_PROXY_SUBSCRIPTION_INVALID: 'PLATFORM_NETWORK_PROXY_SUBSCRIPTION_INVALID',
  /** `PROXY_URL` (legacy proxychains) is active → selective routing cannot be enabled. */
  PLATFORM_NETWORK_PROXY_GLOBAL_PROXY_ACTIVE: 'PLATFORM_NETWORK_PROXY_GLOBAL_PROXY_ACTIVE',
  /**
   * `ruleMode: 'smart'` requires both `desiredArtifacts.geoip` and `.geosite`
   * (desired, not necessarily installed on this instance yet).
   */
  PLATFORM_NETWORK_PROXY_GEODATA_MISSING: 'PLATFORM_NETWORK_PROXY_GEODATA_MISSING',
} as const;

export type PlatformErrorCode = (typeof PLATFORM_ERROR_CODES)[keyof typeof PLATFORM_ERROR_CODES];

export const ADMIN_ERROR_CODES = {
  ADMIN_ACCESS_DENIED: 'ADMIN_ACCESS_DENIED',
  ADMIN_REAUTH_REQUIRED: 'ADMIN_REAUTH_REQUIRED',
  ADMIN_REASON_REQUIRED: 'ADMIN_REASON_REQUIRED',
  ADMIN_FEATURE_DISABLED: 'ADMIN_FEATURE_DISABLED',
  /**
   * Administrative mutation quota exhausted or the shared limiter authority is
   * unavailable (fail closed). Maps to tRPC TOO_MANY_REQUESTS.
   */
  ADMIN_RATE_LIMITED: 'ADMIN_RATE_LIMITED',
} as const;

export type AdminErrorCode = (typeof ADMIN_ERROR_CODES)[keyof typeof ADMIN_ERROR_CODES];

export const MANAGED_ERROR_CODES = {
  /** M06 canonical legacy-mutation denial returned by ManagedResourceGuard. */
  RESOURCE_MANAGED_BY_PLATFORM: 'RESOURCE_MANAGED_BY_PLATFORM',
  MANAGED_RESOURCE_BY_PLATFORM: 'MANAGED_RESOURCE_BY_PLATFORM',
  MANAGED_SETTING_BY_ADMIN: 'MANAGED_SETTING_BY_ADMIN',
  MANAGED_POLICY_ENFORCED: 'MANAGED_POLICY_ENFORCED',
  /** Path is not in the finite settings registry. */
  MANAGED_SETTING_UNKNOWN_PATH: 'MANAGED_SETTING_UNKNOWN_PATH',
  /** Path is secret / sensitive and never policy-eligible. */
  MANAGED_SETTING_SECRET_PATH: 'MANAGED_SETTING_SECRET_PATH',
  /** Path is not applicable to the requested client surface. */
  MANAGED_SETTING_INAPPLICABLE_CLIENT: 'MANAGED_SETTING_INAPPLICABLE_CLIENT',
  /** Path is registered but not platform-policy eligible. */
  MANAGED_SETTING_NOT_POLICY_ELIGIBLE: 'MANAGED_SETTING_NOT_POLICY_ELIGIBLE',
  /** Value failed the registry Zod schema. */
  MANAGED_SETTING_INVALID_VALUE: 'MANAGED_SETTING_INVALID_VALUE',
  /**
   * Batch mutation exceeds the managed-agent guard id limit.
   * `details.max` carries the allowed upper bound for client i18n (`{{max}}`).
   */
  MANAGED_AGENT_BATCH_LIMIT: 'MANAGED_AGENT_BATCH_LIMIT',
} as const;

export type ManagedErrorCode = (typeof MANAGED_ERROR_CODES)[keyof typeof MANAGED_ERROR_CODES];

/**
 * Stable connector / binding / OAuth error codes (admin + end-user connector flows).
 * Contract schemas and UI mappers must derive from this catalog — never a local literal list.
 */
export const PLATFORM_CONNECTOR_ERROR_CODES = {
  PLATFORM_CONNECTOR_BINDING_NOT_FOUND: 'PLATFORM_CONNECTOR_BINDING_NOT_FOUND',
  PLATFORM_CONNECTOR_BINDING_OWNERSHIP_MISMATCH: 'PLATFORM_CONNECTOR_BINDING_OWNERSHIP_MISMATCH',
  PLATFORM_CONNECTOR_CONFIRMATION_REQUIRED: 'PLATFORM_CONNECTOR_CONFIRMATION_REQUIRED',
  PLATFORM_CONNECTOR_CREDENTIAL_NOT_CONFIGURED: 'PLATFORM_CONNECTOR_CREDENTIAL_NOT_CONFIGURED',
  PLATFORM_CONNECTOR_NOT_FOUND: 'PLATFORM_CONNECTOR_NOT_FOUND',
  PLATFORM_CONNECTOR_NOT_PUBLISHED: 'PLATFORM_CONNECTOR_NOT_PUBLISHED',
  PLATFORM_CONNECTOR_OAUTH_CALLBACK_INVALID: 'PLATFORM_CONNECTOR_OAUTH_CALLBACK_INVALID',
  PLATFORM_CONNECTOR_OAUTH_STATE_EXPIRED: 'PLATFORM_CONNECTOR_OAUTH_STATE_EXPIRED',
  PLATFORM_CONNECTOR_OAUTH_STATE_INVALID: 'PLATFORM_CONNECTOR_OAUTH_STATE_INVALID',
  PLATFORM_CONNECTOR_OAUTH_STATE_REPLAYED: 'PLATFORM_CONNECTOR_OAUTH_STATE_REPLAYED',
  PLATFORM_CONNECTOR_RETURN_TO_INVALID: 'PLATFORM_CONNECTOR_RETURN_TO_INVALID',
  PLATFORM_CONNECTOR_RATE_LIMITED: 'PLATFORM_CONNECTOR_RATE_LIMITED',
  PLATFORM_CONNECTOR_RESOURCE_MISMATCH: 'PLATFORM_CONNECTOR_RESOURCE_MISMATCH',
  PLATFORM_CONNECTOR_SCOPE_NOT_ALLOWED: 'PLATFORM_CONNECTOR_SCOPE_NOT_ALLOWED',
  PLATFORM_CONNECTOR_SECRET_EXPOSURE_BLOCKED: 'PLATFORM_CONNECTOR_SECRET_EXPOSURE_BLOCKED',
  PLATFORM_CONNECTOR_SSRF_BLOCKED: 'PLATFORM_CONNECTOR_SSRF_BLOCKED',
  PLATFORM_CONNECTOR_STDIO_UNSUPPORTED: 'PLATFORM_CONNECTOR_STDIO_UNSUPPORTED',
  PLATFORM_CONNECTOR_TOOL_DENIED: 'PLATFORM_CONNECTOR_TOOL_DENIED',
  PLATFORM_CONNECTOR_TRANSPORT_UNSUPPORTED: 'PLATFORM_CONNECTOR_TRANSPORT_UNSUPPORTED',
} as const;

export type PlatformConnectorErrorCode =
  (typeof PLATFORM_CONNECTOR_ERROR_CODES)[keyof typeof PLATFORM_CONNECTOR_ERROR_CODES];

/** Non-empty tuple of connector error codes for Zod `z.enum(...)`. */
export const PLATFORM_CONNECTOR_ERROR_CODE_VALUES = Object.values(
  PLATFORM_CONNECTOR_ERROR_CODES,
) as [PlatformConnectorErrorCode, ...PlatformConnectorErrorCode[]];

export const ENTERPRISE_ERROR_CODES = {
  ...PLATFORM_ERROR_CODES,
  ...ADMIN_ERROR_CODES,
  ...MANAGED_ERROR_CODES,
  ...PLATFORM_CONNECTOR_ERROR_CODES,
} as const;

export type EnterpriseErrorCode =
  PlatformErrorCode | AdminErrorCode | ManagedErrorCode | PlatformConnectorErrorCode;

const ALL_CODE_VALUES = new Set<string>(Object.values(ENTERPRISE_ERROR_CODES));

export const isEnterpriseErrorCode = (value: string): value is EnterpriseErrorCode =>
  ALL_CODE_VALUES.has(value);
