import type { PartialDeep } from 'type-fest';
import { z } from 'zod';

import type { LobeToolRenderType } from '../../tool';

/**
 * SERVER-owned resume-interaction kind (M10 PR-049 · RR5-2). Recorded on a pending tool message by
 * the runtime when the operation parks, from the tool's VERIFIED intervention type — never a client
 * field. `approval` = a sensitive op awaiting approve/reject (security block / `required` policy /
 * unknown tool); `toolResult` = a human-answer tool whose result IS the human's input (a tool that
 * declares its OWN `humanIntervention: 'always'`, e.g. lobe-agent `askUserQuestion`). A resume must
 * match the persisted kind EXACTLY — `resumeApproval` only on `approval`, `resumeToolResult` only on
 * `toolResult` — so the two interaction paths can never cross-mutate one tool. The public message
 * API strips this key from client input so it stays server-owned.
 */
export type ResumeInteractionKind = 'approval' | 'toolResult';

/**
 * Server-authored provenance for a resumable human-intervention placeholder. Public message
 * mutations must never be allowed to author these fields. The fingerprint binds the immutable tool
 * call identity without persisting its arguments in operation metadata.
 */
export interface ResumeToolProvenance {
  assistantMessageId: string;
  fingerprint: string;
  kind: ResumeInteractionKind;
  messageId: string;
  operationId: string;
  toolCallId: string;
}

export const fingerprintResumeToolCall = async (tool: {
  apiName?: string;
  arguments?: string;
  identifier?: string;
  toolCallId?: string;
  type?: string;
}): Promise<string> => {
  const payload = JSON.stringify([
    tool.identifier ?? '',
    tool.apiName ?? '',
    tool.toolCallId ?? '',
    tool.type ?? '',
    tool.arguments ?? '',
  ]);
  const digest = await globalThis.crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(payload),
  );
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
};

// ToolIntervention must be defined first to avoid circular dependency
export interface ToolIntervention {
  /** Server-owned resume-interaction kind — see {@link ResumeInteractionKind}. */
  kind?: ResumeInteractionKind;
  /** Server-owned binding for a pending resumable tool placeholder. */
  provenance?: ResumeToolProvenance;
  rejectedReason?: string;
  status?: 'pending' | 'approved' | 'rejected' | 'aborted' | 'none';
}

export const ToolInterventionSchema = z.object({
  kind: z.enum(['approval', 'toolResult']).optional(),
  provenance: z
    .object({
      assistantMessageId: z.string(),
      fingerprint: z.string(),
      kind: z.enum(['approval', 'toolResult']),
      messageId: z.string(),
      operationId: z.string(),
      toolCallId: z.string(),
    })
    .optional(),
  rejectedReason: z.string().optional(),
  status: z.enum(['pending', 'approved', 'rejected', 'aborted', 'none']).optional(),
});

export interface ChatPluginPayload {
  apiName: string;
  arguments: string;
  identifier: string;
  intervention?: ToolIntervention;
  type: LobeToolRenderType;
}

/**
 * Tool source indicates where the tool comes from
 */
export type ToolSource = 'builtin' | 'client' | 'mcp' | 'composio' | 'lobehubSkill';

/**
 * Tool executor indicates where the tool is executed for a given invocation.
 * Orthogonal to ToolSource (origin): executor describes dispatch target.
 */
export type ToolExecutor = 'client' | 'server';

export interface ChatToolPayload {
  apiName: string;
  arguments: string;
  /**
   * Tool executor: dispatch target for this invocation.
   */
  executor?: ToolExecutor;
  id: string;
  identifier: string;
  intervention?: ToolIntervention;
  result_msg_id?: string;
  /**
   * Tool source indicates where the tool comes from
   */
  source?: ToolSource;
  thoughtSignature?: string;
  type: LobeToolRenderType;
}

/**
 * Tool execution result from tool messages
 */
export interface ChatToolResult {
  content: string | null;
  error?: any;
  id: string;
  state?: any;
}

/**
 * Chat tool payload with merged execution result
 */
export interface ChatToolPayloadWithResult extends ChatToolPayload {
  intervention?: ToolIntervention;
  result?: ChatToolResult;
  result_msg_id?: string;
}

export interface ToolsCallingContext {
  topicId?: string;
}
/**
 * The function that the model called.
 */
export interface ToolFunction {
  /**
   * The arguments to call the function with, as generated by the model in JSON
   * format. Note that the model does not always generate valid JSON, and may
   * hallucinate parameters not defined by your function schema. Validate the
   * arguments in your code before calling your function.
   */
  arguments: string;

  /**
   * The name of the function to call.
   */
  name: string;
}

export interface MessageToolCall {
  /**
   * The function that the model called.
   */
  function: ToolFunction;

  /**
   * The ID of the tool call.
   */
  id: string;

  thoughtSignature?: string;
  /**
   * The type of the tool. Currently, only `function` is supported.
   */
  type: 'function' | string;
}

export type MessageToolCallChunk = PartialDeep<MessageToolCall> & { index: number };

export const MessageToolCallSchema = z.object({
  function: z.object({
    arguments: z.string(),
    name: z.string(),
  }),
  id: z.string(),
  type: z.string(),
});

export const ChatToolPayloadSchema = z.object({
  apiName: z.string(),
  arguments: z.string(),
  id: z.string(),
  identifier: z.string(),
  intervention: ToolInterventionSchema.optional(),
  result_msg_id: z.string().optional(),
  thoughtSignature: z.string().optional(),
  type: z.string(),
});

/**
 * Chat message error object
 */
export interface ChatMessagePluginError {
  body?: any;
  message: string;
  type: string;
}
