/** Client-safe target-type tokens for the operation-log column filter. */
export const AUDIT_LOG_TARGET_TYPES = [
  'agent',
  'agent_dependency_validation',
  'audit_event',
  'audit_export',
  'audit_policy',
  'audit_retention_run',
  'authSettings',
  'branding',
  'connector',
  'connector_binding',
  'connector_governance',
  'email_delivery',
  'identity_provider',
  'identity_provider_test',
  'identity_provider_validation',
  'legal_hold',
  'managed_policy',
  'model',
  'permission',
  'platform_global_credential',
  'platform_global_credential_upload',
  'platform_job',
  'provider',
  'secret_rotation',
  'settings',
  'settings_validation',
  'sidebarLayout',
  'skill',
  'system',
  'task_template',
  'topic',
  'user',
  'user_list',
] as const;
