import type { AIChatModelCard } from '../types/aiModel';

const RELEASED_AT = '2026-08-11';

const cursorChatModels: AIChatModelCard[] = [
  {
    abilities: { functionCall: false, reasoning: false, vision: true },
    contextWindowTokens: 200_000,
    description: "Cursor's in-house coding model.",
    displayName: 'Composer 2.5',
    enabled: true,
    family: 'composer',
    generation: 'composer-2.5',
    id: 'composer-2.5',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: false },
    contextWindowTokens: 200_000,
    description: 'Cursor-hosted Grok 4.6 at high reasoning effort.',
    displayName: 'Cursor Grok 4.6',
    enabled: true,
    family: 'grok',
    generation: 'grok-4.6',
    id: 'cursor-grok-4.6-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'Claude Opus 5 with a 1M context window and high thinking effort.',
    displayName: 'Claude Opus 5 1M Thinking',
    enabled: true,
    family: 'claude',
    generation: 'claude-5',
    id: 'claude-opus-5-thinking-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'Claude Sonnet 5 with a 1M context window and high thinking effort.',
    displayName: 'Claude Sonnet 5 1M Thinking',
    enabled: true,
    family: 'claude',
    generation: 'claude-5',
    id: 'claude-sonnet-5-thinking-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'GPT-5.6 Sol with a 1M context window at high reasoning effort.',
    displayName: 'GPT-5.6 Sol 1M High',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.6',
    id: 'gpt-5.6-sol-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 200_000,
    description: 'OpenAI Codex 5.3 at high reasoning effort.',
    displayName: 'Codex 5.3 High',
    enabled: true,
    family: 'gpt',
    generation: 'gpt-5.3',
    id: 'gpt-5.3-codex-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 200_000,
    description: 'Gemini 3.7 Flash at high reasoning effort.',
    displayName: 'Gemini 3.7 Flash',
    enabled: true,
    family: 'gemini',
    generation: 'gemini-3.7',
    id: 'gemini-3.7-flash-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: false, vision: false },
    contextWindowTokens: 200_000,
    description: 'Lets Cursor pick a model for each message.',
    displayName: 'Auto (Cursor)',
    enabled: true,
    family: 'cursor',
    id: 'auto',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: false },
    contextWindowTokens: 200_000,
    description: 'Cursor-hosted Grok 4.5 at high reasoning effort.',
    displayName: 'Cursor Grok 4.5',
    enabled: false,
    family: 'grok',
    generation: 'grok-4.5',
    id: 'cursor-grok-4.5-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'Claude Opus 5 with a 1M context window and extra-high thinking effort.',
    displayName: 'Claude Opus 5 1M Extra High Thinking',
    enabled: false,
    family: 'claude',
    generation: 'claude-5',
    id: 'claude-opus-5-thinking-xhigh',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: true },
    contextWindowTokens: 1_000_000,
    description: 'GPT-5.6 Sol with a 1M context window at extra-high reasoning effort.',
    displayName: 'GPT-5.6 Sol 1M Extra High',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.6',
    id: 'gpt-5.6-sol-xhigh',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: false, vision: true },
    contextWindowTokens: 200_000,
    description: 'GPT-5.2 as served by Cursor.',
    displayName: 'GPT-5.2',
    enabled: false,
    family: 'gpt',
    generation: 'gpt-5.2',
    id: 'gpt-5.2',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: false },
    contextWindowTokens: 200_000,
    description: 'Kimi K3 at high reasoning effort.',
    displayName: 'Kimi K3 High',
    enabled: false,
    family: 'kimi',
    generation: 'kimi-k3',
    id: 'kimi-k3-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
  {
    abilities: { functionCall: false, reasoning: true, vision: false },
    contextWindowTokens: 200_000,
    description: 'GLM 5.2 at high reasoning effort.',
    displayName: 'GLM 5.2',
    enabled: false,
    family: 'glm',
    generation: 'glm-5.2',
    id: 'glm-5.2-high',
    releasedAt: RELEASED_AT,
    type: 'chat',
  },
];

export default cursorChatModels;
