export type { BrowserSessionRegistryOptions } from './contextRegistry';
export {
  assertWritable,
  createBrowserSessionRegistry,
  DEFAULT_BROWSER_SESSION_EPHEMERAL_IDLE_TTL_MS,
  DEFAULT_BROWSER_SESSION_IDLE_TTL_MS,
  DEFAULT_BROWSER_SESSION_MAX_CONTEXTS,
  DEFAULT_BROWSER_SESSION_SWEEP_INTERVAL_MS,
  disposeAllBrowserSessions,
  getBrowserSessionProviderState,
  getBrowserSessionRegistry,
  installBrowserSessionRegistryForTests,
  isBrowserSessionWritable,
  resetAndReplaceBrowserSessionRegistryAfter,
  resetBrowserSessionRegistryForTests,
  setBrowserSessionProviderState,
  startBrowserSessionIdleSweep,
  stopBrowserSessionIdleSweep,
  summarizeBrowserSessionContext,
} from './contextRegistry';
export type {
  ApplySetCookieOptions,
  CookieJarInspection,
  CookieRecord,
  CookieSeed,
  ReplaceCookieFamilyParams,
  SeedBrowserCookieJarOptions,
} from './cookieJar';
export {
  applySetCookieToBrowserCookieJar,
  clearBrowserCookieJarTombstone,
  cookieFamilyName,
  createBrowserCookieJar,
  DEFAULT_BROWSER_COOKIE_JAR_DIR_NAME,
  deleteBrowserCookieJar,
  ensureBrowserCookieJarFile,
  forgetCreatedBrowserCookieJars,
  inspectBrowserCookieJar,
  isAllowedCookieName,
  isBrowserCookieJarTombstoned,
  isCookieFamilyMember,
  isSafeCookieSeed,
  LEGACY_DEVICE_BROWSER_COOKIE_JAR_DIR_NAME,
  parseNetscapeCookieJarText,
  purgeExpiredBrowserCookies,
  readBrowserCookieJar,
  replaceBrowserCookieFamily,
  resetBrowserCookieJars,
  resolveBrowserCookieJarPath,
  seedBrowserCookieJar,
  snapshotCreatedBrowserCookieJars,
  sweepOrphanBrowserCookieJars,
  tombstoneBrowserCookieJar,
  writeBrowserCookieJarRecords,
} from './cookieJar';
export {
  buildBrowserSessionBindingDigest,
  buildBrowserSessionLookupKey,
  digestBrowserSessionMaterial,
  normalizeBrowserSessionAcquireInput,
  normalizeBrowserSessionIdentity,
  normalizeBrowserSessionOrigin,
} from './identity';
export type {
  BrowserSessionBeforeDisposeListener,
  BrowserSessionInvalidateListener,
} from './lifecycle';
export {
  createBrowserSessionOwnerLease,
  disposeBrowserSessionResources,
  isBrowserSessionActive,
  isBrowserSessionLeaseHeldBy,
  markBrowserSessionInvalidated,
  markBrowserSessionReleased,
  notifyBrowserSessionBeforeDispose,
  notifyBrowserSessionInvalidated,
  onBrowserSessionBeforeDispose,
  onBrowserSessionInvalidate,
} from './lifecycle';
export type {
  LibcurlMultiDriver,
  LibcurlMultiDriverStats,
  LibcurlPoolIdentity,
  LibcurlProbeResult,
  PersistentImpersonateFetchOptions,
  PersistentPoolResolution,
} from './transport';
export {
  CONNECT_TIMEOUT_MS,
  createLibcurlMultiDriver,
  createPersistentImpersonateFetch,
  drainAllPersistentTransport,
  drainPersistentTransportForScope,
  drainPersistentTransportWhere,
  getSharedLibcurlMultiDriver,
  LIBCURL_IMPERSONATE_PATH_ENV,
  probeLibcurlImpersonate,
  resetLibcurlImpersonateProbeForTests,
  resetSharedLibcurlMultiDriverForTests,
  resolveLibcurlImpersonatePath,
  TRANSPORT_POOL_DRAINED,
} from './transport';
export type { BrowserSessionTransportHandle, BrowserSessionTransportPool } from './transportPool';
export {
  buildBrowserSessionTransportPoolKey,
  createBrowserSessionTransportPool,
  registerBrowserSessionScopeDrain,
} from './transportPool';
export type {
  BrowserSessionAcquireInput,
  BrowserSessionContext,
  BrowserSessionContextSummary,
  BrowserSessionCookieJarRef,
  BrowserSessionLifecycleStatus,
  BrowserSessionOwnerLease,
  BrowserSessionProviderNamespaces,
  BrowserSessionProviderState,
  BrowserSessionRegistry,
  BrowserSessionWriteFence,
} from './types';
export {
  BROWSER_SESSION_RESETTING_CODE,
  BrowserSessionError,
  BrowserSessionResettingError,
  isBrowserSessionResettingError,
} from './types';
